### ISSUE TITLE
Ollama Support

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [gladcolor/LLM-Geo#2]
Hello and thanks for this beautiful repository.

Do you have plans for integrating self hosted open source LLMs? If so, can you please consider using [Ollama](https://ollama.ai/)?

Best,
Orkut

**Comment by gladcolor** [comment]
Thanks for your comments, Orkut!

Our team is closely watching the progress of open-sourced LLMs; however, we have no confidence that some of them are better than GPT-4 in terms of task planning and coding. The cheaper GPT-3.5 API cannot perform the task also. So, our team has no plan to introduce other LLMs yet. If you need to use other LLMs, you can override the functions requesting LLM response in the LLm_Geo_kernel.py file. These functions have "LLM" in their names.

Thanks very much,
Huan

**Comment by orkutmuratyilmaz** [comment]
Dear Huan,

Thanks for your kind reply and beautiful recommendation. I'll give it a try on overriding, as you mentioned.

Best,
Orkut

**Comment by paolaos** [comment]
Hi @orkutmuratyilmaz! Did you end up giving it a try? Interested to know how it performed :)

**Comment by orkutmuratyilmaz** [comment]
Not yet, but I have plans for trying it next week:)

**Comment by vamsivarma** [comment]
Hello,

Do you have any plans to support ollama models ? or is it already in place

**Comment by gladcolor** [comment]
Currently no such plans. Per my knowledge, most other models are still at the level of GPT 3.5, which is insufficient to create the qualified solution graphs during our test last year. May Gemini 1.0 Ultra or above have the same or better capability than GPT-4. We will consider Gemini in the future. Our current financial status does not support having other API subscriptions. Therefore, we also pay very close attention to the open source LLMs.
