### ISSUE TITLE
New major release of the openAI SDK

### ISSUE THREAD

**Issue by JeromeVigne** [gladcolor/LLM-Geo#5]
Hi,

OpenAI has released a new major version of their SDK: [LINK](https://github.com/openai/openai-python/discussions/742).

I migrated my local project to openai 1.10.0. If of interest, happy to create a new branch and submit, or let me know how to best contribute.

**Comment by gladcolor** [comment]
Hello @JeromeVigne ! Thanks for your reminder! It would be great if you could contribute to the SDK migration.

**Comment by JeromeVigne** [comment]
Hi,
@gladcolor: You can copy from this commit: https://github.com/JeromeVigne/LLM-geo/commit/46ce54e2e40dc32fb280d4d1bd589a1c5be52c79

Can you cherry pick the files: helper.py, LLM_Geo_kernel.py, LLM_Geo_API4.ipynb and requirements.txt ?

**Comment by JeromeVigne** [comment]
Or let me know what is the easiest way to contribute, if you add me as contributor I can create a new branch and commit in this repo

**Comment by gladcolor** [comment]
Thanks, @JeromeVigne ! That is a bit. I am traveling and will update and test the code next week.

**Comment by gladcolor** [comment]
@JeromeVigne Updated! Note `dict.key` on my side does not work, so I use `dict["key"]`.
